# Generated by Django 3.0.5 on 2020-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalmap', '0002_credentialsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalmap',
            old_name='hiv',
            new_name='asthma',
        ),
        migrations.RenameField(
            model_name='medicalmap',
            old_name='transplant',
            new_name='immuno',
        ),
        migrations.AddField(
            model_name='medicalmap',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalmap',
            name='travel_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalmap',
            name='work',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CredentialsModel',
        ),
    ]
