# Generated by Django 3.0.5 on 2020-04-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coronaapp',
            name='status',
        ),
        migrations.AddField(
            model_name='coronaapp',
            name='degree',
            field=models.IntegerField(default=-1),
        ),
    ]
