# Generated by Django 3.0.5 on 2020-04-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronaapp',
            name='Latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coronaapp',
            name='Longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coronaapp',
            name='Status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
