# Generated by Django 3.0.5 on 2020-04-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0002_auto_20200405_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronaapp',
            name='Latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coronaapp',
            name='Longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coronaapp',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
