# Generated by Django 3.0.5 on 2020-04-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0002_auto_20200423_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalmap',
            name='cough',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicalmap',
            name='country_travelled',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicalmap',
            name='current_state',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicalmap',
            name='domestic_airport_from',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicalmap',
            name='domestic_airport_to',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicalmap',
            name='fever',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicalmap',
            name='symptoms_improvement',
            field=models.IntegerField(default=0),
        ),
    ]
