# Generated by Django 3.0.5 on 2020-04-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0003_auto_20200423_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalmap',
            name='med_uuid',
            field=models.CharField(default='a', max_length=1000),
        ),
    ]
