# Generated by Django 3.0.5 on 2020-04-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0003_auto_20200405_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coronaapp',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='coronaapp',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='coronaapp',
            old_name='Status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='coronaapp',
            name='Name',
        ),
        migrations.AddField(
            model_name='coronaapp',
            name='name',
            field=models.CharField(blank=True, default='a', max_length=100),
        ),
    ]
