# Generated by Django 3.0.5 on 2020-04-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0004_auto_20200406_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('diabetes', models.BooleanField(default=False)),
                ('kidney', models.BooleanField(default=False)),
                ('heart', models.BooleanField(default=False)),
                ('lungs', models.BooleanField(default=False)),
                ('stroke', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('hiv', models.BooleanField(default=False)),
                ('transplant', models.BooleanField(default=False)),
            ],
        ),
    ]
