# Generated by Django 3.0.5 on 2020-04-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0005_medicalmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronaapp',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
    ]
