# Generated by Django 3.0.5 on 2020-04-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0006_coronaapp_diabetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalmap',
            name='airport_from',
            field=models.CharField(blank=True, default='Delhi', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalmap',
            name='airport_to',
            field=models.CharField(blank=True, default='Mumbai', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalmap',
            name='current_state',
            field=models.CharField(blank=True, default='Maharashtra', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalmap',
            name='fever',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'If Yes, then Temperature between 98.6 to 100.4 ^C'), (2, 'If Yes, then Temperature between 100.4 to 104 ^C'), (3, 'If Yes, then fever that comes and goes'), (4, 'If Yes, then have not checked the Temperature')], default=0),
        ),
    ]
