# Generated by Django 3.0.5 on 2020-04-16 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0008_auto_20200410_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coronaapp',
            options={},
        ),
        migrations.RemoveField(
            model_name='coronaapp',
            name='created',
        ),
        migrations.RemoveField(
            model_name='coronaapp',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='coronaapp',
            name='name',
        ),
        migrations.AddField(
            model_name='coronaapp',
            name='timeslot',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coronaapp',
            name='uuid',
            field=models.CharField(default='a', max_length=1000),
        ),
    ]
