# Generated by Django 3.0.5 on 2020-04-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0009_auto_20200416_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronaapp',
            name='timeslot',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
